spring:
  profiles:
    active: local
  datasource:
    primary:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/subscription_service?characterEncoding=UTF-8
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      minimumIdle: 2
      maximumPoolSize: 5
    secondary:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/subscription_service?characterEncoding=UTF-8
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      minimumIdle: 2
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8901
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: ./logs/server.log
    path: ./logs/
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 7

---
spring:
  config.activate:
    on-profile: local
  config:
    import: file:./env.properties
  datasource:
    primary:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/subscription_service?characterEncoding=UTF-8
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
    secondary:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/subscription_service?characterEncoding=UTF-8
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
